image: juanpgenovese/site:1.0

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - output/jpgenovese
    - output/resume

variables:
  JEKYLL_ENV: production

build:
  stage: build
  script:
    - ./bin/build.sh
  artifacts:
    expire_in: 1 hour
    paths:
      - output/jpgenovese
      - output/resume
test:
  stage: test
  dependencies: 
    - build
  script:
    - cd output/jpgenovese && webfsd -p 4000 -f index.html
    - http GET http://127.0.0.1:4000 | grep "Juan Pablo Genovese"
    - linkchecker http://127.0.0.1:4000/

deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./output/jpgenovese/* "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$BLOG_TARGET_DIR/"
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./output/resume/resume.html "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$RESUME_TARGET_DIR/index.html"
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./output/resume/resume.pdf "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$RESUME_TARGET_DIR/jpg-resume.pdf"
  only:
  - master