image: juanpgenovese/jekyll:3.8.3

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - jpgenovese
    - resume/out

variables:
  JEKYLL_ENV: production

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    expire_in: 1 hour
    paths:
      - jpgenovese
      - resume/out
test:
  stage: test
  dependencies: 
    - build
  script:
    - cd jpgenovese && webfsd -p 4000 -f index.html
    - http GET http://127.0.0.1:4000 | grep "Juan Pablo Genovese"
    - linkchecker http://127.0.0.1:4000/

deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./jpgenovese/* "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$BLOG_TARGET_DIR/"
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./resume/out/resume.html "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$RESUME_TARGET_DIR/index.html"
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./resume/out/resume.pdf "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$RESUME_TARGET_DIR/jpg-resume.pdf"
  only:
  - master