image: juanpgenovese/jekyll:3.8.3

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - jpgenovese

variables:
  JEKYLL_ENV: production

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    expire_in: 1 hour
    paths:
      - jpgenovese
test:
  stage: test
  dependencies: 
    - build
  script:
    - cd jpgenovese && webfsd -p 4000 -f index.html
    - http GET http://127.0.0.1:4000 | grep "Juan Pablo Genovese"
    - linkchecker http://127.0.0.1:4000/
  artifacts:
    paths:
      - jpgenovese

deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - sshpass -p "$ACCESS_SECRET" scp -r -o 'StrictHostKeyChecking no' ./jpgenovese/* "$ACCESS_TOKEN@$HOST:/home/$ACCESS_TOKEN/$TARGET_DIR/"
  only:
  - master