image: juanpgenovese/jekyll:3.8.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

build:
  stage: build
  script:
    - bundle exec jekyll build -d jpgenovese
  artifacts:
    expire_in: 1 month
    paths:
      - jpgenovese
test:
  stage: test
  script:
    - cd /builds/project-0/jpgenovese && webfsd -p 4000 -f index.html
    - http GET http://127.0.0.1:4000 | grep "Juan Pablo Genovese"
    - linkchecker http://127.0.0.1:4000/
  artifacts:
    paths:
    - jpgenovese

deploy:
  stage: deploy
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
  artifacts:
    paths:
    - jpgenovese
  only:
  - master